import type { Product } from '../../../types';

export const mockProducts: Product[] = [
  {
    id: 'p1',
    title: 'Livro de Matemática 11ª Classe (Manual + Caderno de Exercícios)',
    category: 'livros',
    price: 6500,
    seller: 'Ana (11ª)',
    img: '/assets/calculation_book_image.png',
    condition: 'usado',
    location: 'Talatona',
    subject: 'Matemática',
    gradeLevel: 11,
    productType: 'material',
    rating: 4.6,
    reviews: 18,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 2).toISOString(),
    description: 'Livro em bom estado. Algumas páginas com marcações leves.',
  },
  {
    id: 'p2',
    title: 'Explicações de Física (12ª) — 2h/semana',
    category: 'servicos',
    price: 25000,
    seller: 'Carlos (13ª)',
    img: '/assets/hero-section-image.png',
    condition: 'novo',
    location: 'Viana',
    subject: 'Física',
    gradeLevel: 12,
    productType: 'servico',
    rating: 4.9,
    reviews: 41,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    description: 'Aulas presenciais em Luanda (Viana) ou online. Preparação para testes.',
  },
  {
    id: 'p3',
    title: 'Calculadora Científica (Casio fx-991EX)',
    category: 'tecnologia',
    price: 18000,
    seller: 'Marta',
    img: '/assets/calculator_image.png',
    condition: 'como_novo',
    location: 'Kilamba',
    subject: 'Matemática',
    gradeLevel: 10,
    productType: 'material',
    rating: 4.8,
    reviews: 12,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 12).toISOString(),
    description: 'Pouco usada. Inclui caixa e manual.',
  },
  {
    id: 'p4',
    title: 'Cadernos A4 200 folhas (Pack 5)',
    category: 'material_escolar',
    price: 9500,
    seller: 'Loja Escolar',
    img: '/assets/beige_backpack_image.png',
    condition: 'novo',
    location: 'Maianga',
    subject: 'Geral',
    gradeLevel: 13,
    productType: 'material',
    rating: 4.2,
    reviews: 9,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24 * 1).toISOString(),
    description: 'Ideal para o ano letivo. Entregas em Luanda (sob consulta).',
  },
];
